tap 'homebrew/bundle'

brew 'openssl'
brew 'coreutils'
brew 'peco'
brew 'git'
brew 'peco'
brew 'python'
brew 'pyenv'
brew 'tmux'
brew 'tree'
brew 'vim', args: ['with-lua', 'with-luajit']
brew 'wget'
brew 'zsh', args: ['disable-etcdir']
brew 'zsh-completions'

